services:

  proxy:
    build:
     context: ./nginx
     dockerfile: Dockerfile.proxy
    image: proxy
    container_name: proxy
    ports:
     - "8080:80"
    depends_on:
     - portal
    networks:
     - asa-network

  dns:
    build:
     context: ./DNS
     dockerfile: Dockerfile
    image: bind9
    container_name: bind9
    ports:
     - "53:53"
    depends_on:
     - proxy

#  email:
#    build:
#     context: ./email
#     dockerfile: Dockerfile
#    image: email
#    container_name: email
#    ports:
#     - "110:110"
#    depends_on:
#     - dns

  portal:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: gabriel
      WORDPRESS_DB_PASSWORD: asa_senha
      WORDPRESS_DB_NAME: asa_2023
    volumes:
     - wordpress:/var/www/html
    networks:
     - asa-network
    depends_on:
     - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: asa_2023
      MYSQL_USER: gabriel
      MYSQL_PASSWORD: asa_senha
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
     - db:/var/lib/mysql
    networks:
     - asa-network

volumes:
  wordpress:
  db:
  #Docker Networks
networks:
 asa-network:
  driver: bridge